version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-dev
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network         # ← adiciona aqui

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongo:27017/appdb
      PORT: 3000
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
